version: '3.9'
services:
  # Express Container  
  backend:
    build:
      context: './server'
      dockerfile: Dockerfile
    image: backend
    restart: always
    ports:
      - 4000:4000
      - 9229:9229
    env_file:
      - ./server/.env
    container_name: chatapp_server
    networks:
      - chatapp
    volumes:
      - /app/node_modules
    develop:
      watch:
        - action: rebuild
          path: ./server/package.json
        - action: rebuild
          path: ./server/package-lock.json
        - action: sync
          path: ./server
          target: /app
          ignore:
            - node_modules/
            - dist/
    depends_on:
      - db
  # React Container
  frontend:
    build:
      context: './client'
      dockerfile: Dockerfile
    image: frontend
    restart: always
    ports:
      - 5173:5173
    env_file:
      - ./client/.env
    container_name: chatapp_client
    networks:
      - chatapp
    volumes:
      - /app/node_modules
    develop:
      watch:
        - action: rebuild
          path: ./client/package.json
        - action: rebuild
          path: ./client/package-lock.json
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
            - dist/
    depends_on:
    - db
  # Postgres Container
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./.db.env
    container_name: chatapp_db
    networks:
      - chatapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # Adminer Container
  adminer:
    image: adminer
    restart: always
    ports:
      - 6500:8080
    container_name: chatapp_adminer
    networks:
      - chatapp
    depends_on:
      - db
networks:
  chatapp:
volumes:
  postgres_data:
  